name: Pipeline DevSecOps

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Instalar dependencias
        run: pip install -r requirements.txt

  sast:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio para SAST
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ejecutar análisis SAST con SonarQube Cloud
        uses: SonarSource/sonarqube-scan-action@v8.2.1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=lucianamayrablancoaranibar
            -Dsonar.projectKey=LucianaMayraBlancoAranibar_app-vulnerable-sesion4
            -Dsonar.sources=.
            -Dsonar.exclusions=.github/**
            -Dsonar.qualitygate.wait=true

  sca:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio para SCA
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependencias del proyecto
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Instalar Snyk CLI
        uses: snyk/actions/setup@master

      - name: Bloquear por vulnerabilidades High o Critical
        run: snyk test --file=requirements.txt --package-manager=pip --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
